runtime: go
api_version: go1.9
module: myservice

inbound_services:
- warmup

automatic_scaling:
  min_idle_instances: 1

handlers:
  - url: /.*
    script: _go_app

env_variables:
  VAULT_ADDR: https://vault.example.com
  VAULT_SECRET_PATH: "repo-name/secret/my-secrets"
  VAULT_GCP_IAM_ROLE: "my-svc-acct-vault-role"
